/* Demo data: Halden Group, a fictional insurer and services company with about 3,100 employees. */
const SEED = () => ({
  company: 'Halden Group',
  settings: JSON.parse(JSON.stringify(CL.DEFAULT_SETTINGS)),
  groups: [
    { id: 'sd',  name: 'Service Desk',       unit: 'Customer Service', location: 'Prague',   fte: 420, strain: 15, note: 'Understaffed after summer attrition' },
    { id: 'co',  name: 'Client Operations',  unit: 'Operations',       location: 'Brno',     fte: 610, strain: 10, note: 'Year-end renewals peak' },
    { id: 'am',  name: 'Account Management', unit: 'Commercial',       location: 'Vienna',   fte: 180, strain: 0 },
    { id: 'sa',  name: 'Sales',              unit: 'Commercial',       location: 'Multiple', fte: 240, strain: 0 },
    { id: 'fi',  name: 'Finance',            unit: 'Finance',          location: 'Prague',   fte: 150, strain: 5, note: 'Q4 close in December' },
    { id: 'hr',  name: 'HR',                 unit: 'People',           location: 'Prague',   fte: 90,  strain: 0 },
    { id: 'it',  name: 'IT',                 unit: 'Technology',       location: 'Prague',   fte: 310, strain: 0 },
    { id: 'bo',  name: 'Back Office',        unit: 'Operations',       location: 'Ostrava',  fte: 520, strain: 0 },
  ],
  initiatives: [
    { id: 'csm', name: 'Client system migration', unit: 'Operations', owner: 'Marta Novák', sponsor: 'COO',
      status: 'approved', color: 0, start: 0, prepWeeks: 5, goLiveWeeks: 3, hypercareWeeks: 4,
      summary: 'Move all client policies and servicing from the legacy core system to the new client platform.',
      impacts: [
        { groupId: 'co', type: 'tool',      intensity: 5, hours: 9,  pct: 100 },
        { groupId: 'sd', type: 'process',   intensity: 3, hours: 6,  pct: 100 },
        { groupId: 'am', type: 'tool',      intensity: 3, hours: 6,  pct: 80 },
        { groupId: 'bo', type: 'migration', intensity: 2, hours: 6,  pct: 60 },
      ] },
    { id: 'tkt', name: 'Ticket management to cloud', unit: 'Technology', owner: 'Jakub Dvořák', sponsor: 'CIO',
      status: 'approved', color: 1, start: 2, prepWeeks: 4, goLiveWeeks: 3, hypercareWeeks: 3,
      summary: 'Replace the on-premise ticketing tool with a cloud service management platform.',
      impacts: [
        { groupId: 'sd', type: 'tool',    intensity: 5, hours: 9,  pct: 100 },
        { groupId: 'it', type: 'tool',    intensity: 3, hours: 8,  pct: 100 },
        { groupId: 'co', type: 'process', intensity: 3, hours: 6,  pct: 100 },
      ] },
    { id: 'tms', name: 'Timesheet tool to cloud', unit: 'Finance', owner: 'Petra Horáková', sponsor: 'CFO',
      status: 'approved', color: 2, start: 11, prepWeeks: 3, goLiveWeeks: 1, hypercareWeeks: 2,
      summary: 'Company-wide switch to a cloud timesheet and absence tool.',
      impacts: [
        { groupId: 'sd', type: 'tool', intensity: 2, hours: 2, pct: 100 },
        { groupId: 'co', type: 'tool', intensity: 2, hours: 2, pct: 100 },
        { groupId: 'am', type: 'tool', intensity: 2, hours: 2, pct: 100 },
        { groupId: 'sa', type: 'tool', intensity: 2, hours: 2, pct: 100 },
        { groupId: 'fi', type: 'tool', intensity: 3, hours: 6, pct: 100 },
        { groupId: 'hr', type: 'tool', intensity: 3, hours: 5, pct: 100 },
        { groupId: 'it', type: 'tool', intensity: 2, hours: 2, pct: 100 },
        { groupId: 'bo', type: 'tool', intensity: 2, hours: 2, pct: 100 },
      ] },
    { id: 'spl', name: 'SharePoint link migration', unit: 'Technology', owner: 'Lukas Weber', sponsor: 'CIO',
      status: 'in_flight', color: 3, start: 0, prepWeeks: 3, goLiveWeeks: 2, hypercareWeeks: 3,
      summary: 'Move team sites to the new tenant. Every saved link and bookmark changes.',
      impacts: [
        { groupId: 'sd', type: 'migration', intensity: 1, hours: 2, pct: 100 },
        { groupId: 'co', type: 'migration', intensity: 1, hours: 2, pct: 100 },
        { groupId: 'am', type: 'migration', intensity: 1, hours: 2, pct: 100 },
        { groupId: 'sa', type: 'migration', intensity: 2, hours: 3, pct: 100 },
        { groupId: 'fi', type: 'migration', intensity: 1, hours: 2, pct: 100 },
        { groupId: 'hr', type: 'migration', intensity: 1, hours: 2, pct: 100 },
        { groupId: 'bo', type: 'migration', intensity: 2, hours: 4, pct: 100 },
      ] },
    { id: 'kbm', name: 'Knowledge base migration and access restrictions', unit: 'Customer Service', owner: 'Eva Svobodová', sponsor: 'Head of Customer Service',
      status: 'approved', color: 4, start: 8, prepWeeks: 3, goLiveWeeks: 2, hypercareWeeks: 3,
      summary: 'Move service articles to a new knowledge base and restrict access by role.',
      impacts: [
        { groupId: 'sd', type: 'process', intensity: 4, hours: 6,  pct: 100 },
        { groupId: 'co', type: 'process', intensity: 3, hours: 4,  pct: 100 },
        { groupId: 'am', type: 'policy',  intensity: 1, hours: 2,  pct: 100 },
      ] },
  ],
  feed: [],
});
if (typeof module !== 'undefined') module.exports = SEED;
